# Уровень 0:
Посчитайте частные производные функций: 𝑓(𝑥,𝑦)=2𝑥2𝑦3+1/𝑥+𝑦2𝑥+7 , а для этой функции также градиент в точке (1,2)

In [4]:
import numpy as np
from scipy.optimize import approx_fprime

In [5]:
def func(x, c0, c1, c2):
    
    return c0 * x[0]**2*x[1]**3 + c1 *x[0] **(-1) + c2*x[0]**2*x[1] + 7

In [6]:
x = np.array([1,2])
c0, c1, c2 = (2, 1, 1)
eps = np.sqrt(np.finfo(float).eps)
approx_fprime(x, func, [eps, eps], c0, c1, c2)

array([35.00000024, 25.00000024])

# Уровень 0:
Посчитайте частные производные функций: 𝑓(𝑥,𝑦)=𝑥2𝑦−𝑠𝑖𝑛(𝑥𝑦)+𝑐𝑜𝑠(𝑥2)+6𝑦

In [7]:
def func(x, c0, c1, c2, c3):
   
    return c0 * x[0]**2*x[1] - c1 *np.sin(x[0]*x[1]) + c2*np.cos(x[0]**2) + c3*x[1]

In [8]:
x = np.ones(2)
c0, c1, c2, c3 = (1, 1, 1, 6)
eps = np.sqrt(np.finfo(float).eps)
approx_fprime(x, func, [eps, eps], c0, c1, c2, c3)

array([-0.22324431,  6.45969766])

# Уровень 1: не сделано!!!
Градиентный спуск своими руками:

In [9]:
def f(x, z0, z1):
    return (z0*x[0]**2) + (z1*x[1]**2)

In [10]:
x = np.array([100, 200])
learning_rate = 0.1
centre = (learning_rate, learning_rate)
cx, cy = centre
z0, z1 = (1, 1)
eps1 = np.sqrt(np.finfo(float).eps)
approx_fprime(x, f, [eps1, eps1], z0, z1)

array([200., 400.])

# 