# Домашнее задание "Продвинутая линейная алгебра". Уровень 0:

# Диагональная, ортогональная, но не единичная(!)

In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
A = np.array([[2, 0], 
             [0, 0.5]])
A

array([[2. , 0. ],
       [0. , 0.5]])

In [4]:
B = LA.inv(A)
B

array([[0.5, 0. ],
       [0. , 2. ]])

In [5]:
C = np.dot(A, B)
C

array([[1., 0.],
       [0., 1.]])

# Верхнетреугольная, ортогональная

In [9]:
A1 = np.array([[2, 0], # Верхнетреугольная
             [2, 0.5]])
A1

array([[2. , 0. ],
       [2. , 0.5]])

In [10]:
B1 = LA.inv(A1)
B1

array([[ 0.5,  0. ],
       [-2. ,  2. ]])

In [11]:
C1 = np.dot(A1, B1)
C1

array([[1., 0.],
       [0., 1.]])

# Нижнетреугольная, ортогональная

In [12]:
A2 = np.array([[2, 2], # Нижнетреугольная, ортогональная
             [0, 0.5]])
A2

array([[2. , 2. ],
       [0. , 0.5]])

In [13]:
B2 = LA.inv(A2)
B2

array([[ 0.5, -2. ],
       [ 0. ,  2. ]])

In [14]:
C2 = np.dot(A2, B2)
C2

array([[1., 0.],
       [0., 1.]])

# Матрица, у которой определитель = 1, и все элементы не равны 0

In [15]:
D = np.array([[2, 4], # Нижнетреугольная, ортогональная
             [1, 2.5]])
D

array([[2. , 4. ],
       [1. , 2.5]])

In [16]:
LA.det(D)

1.0

# Найдите собственные значения и собственные вектора матриц:

In [17]:
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [18]:
w,v = LA.eig(m)

In [19]:
w #Собственные числа входной матрицы

array([1., 4.])

In [20]:
v #Собственные векторы входной матрицы

array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]])

# Уровень 1:

# Найдите спектральное разложение матрицы:

In [22]:
from sklearn.decomposition import PCA
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [23]:
pca = PCA(n_components=2)
pca.fit(m)
PCA(n_components=2)
print(pca.explained_variance_ratio_)
print(pca.singular_values_)


[1.00000000e+00 2.81351049e-34]
[1.00000000e+00 1.67735223e-17]


# Постройте зависимость качества восстановления рукописных цифр (MNIST) в зависимости от различного количества компонент PCA. В качестве метрики различия предлагаю использовать MSE.*

# не сделано!!!