In [1]:
import numpy as np
a = np.arange(9, 0, -1)
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [2]:
import numpy as np
n = int(input('Введите размерность матрицы '))
a=np.eye(n)
print(a)
diag = np.diag(a)
print(sum(diag))

Введите размерность матрицы 5
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
5.0


In [5]:
import numpy as np
from numpy import linalg
M1 = np.array([[4, 2, 2], [1, 3, 0], [0, 5, 4]]) # Матрица (левая часть системы)
M2 = np.array([4, 12, -3]) # Вектор (правая часть системы)
np.linalg.solve(M1, M2)

array([ 1.8,  3.4, -5. ])

In [6]:
np.allclose(np.dot(M1, linalg.solve(M1, M2)),M2 ) # проверка верности

True

In [1]:
import numpy as np
users_stats_list = []
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

next_user_stats_lenght = np.linalg.norm(next_user_stats)
for i in users_stats:
    users_stats_lenght = np.linalg.norm(i)
    cos = np.dot( i, next_user_stats ) / ( users_stats_lenght * next_user_stats_lenght )
    users_stats_list.append(cos)
max_element = max(users_stats_list)  
max_element

0.9486832980505138